---
- name: Clone or update dotfiles
  hosts: all
  become: yes
  remote_user: admin
  vars:
    repo_url: 'https://github.com/iobitt/dotfiles.git'
    branch: 'server'
  tasks:
    - name: Clone or update dotfiles repo
      ansible.builtin.git:
        repo: '{{ repo_url }}'
        dest: ~/dotfiles
        version: '{{ branch }}'

    - name: Create a symbolic link for scripts folder
      ansible.builtin.file:
        src: 'dotfiles/scripts'
        dest: scripts
        state: link

    - name: Create a symbolic link pushgateway.service
      ansible.builtin.file:
        src: '~/dotfiles/systemd/pushgateway.service'
        dest: /etc/systemd/system/pushgateway.service
        state: link

    - name: Create a symbolic link send-ps-metrics.service
      ansible.builtin.file:
        src: '~/dotfiles/systemd/send-ps-metrics.service'
        dest: /etc/systemd/system/send-ps-metrics.service
        state: link

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Make sure a pushgateway service unit is running
      ansible.builtin.systemd:
        state: started
        name: pushgateway

    - name: Make sure a send-ps-metrics service unit is running
      ansible.builtin.systemd:
        state: started
        name: send-ps-metrics
